version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8085:8085"
    image: maheshbobby/docker-url-shortener:latest
    restart: unless-stopped
    environment:
      REDIS_URL: redis:6379
    links:
      - "redis:redis"
  redis:
    image: "redis:4.0"
    ports:
     - "6379:6379"